// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDuXWzwCHZeImnvk1f4DOckeaPYXfEyzgE',
    appId: '1:104895741192:web:60231cd34ff9f692f540bd',
    messagingSenderId: '104895741192',
    projectId: 'employee-576ed',
    authDomain: 'employee-576ed.firebaseapp.com',
    storageBucket: 'employee-576ed.appspot.com',
    measurementId: 'G-GXCJXCS2YZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDSujxe06saKLGOOiY-mERCFvMgAa75vhE',
    appId: '1:104895741192:android:4179fe284ad3a8c9f540bd',
    messagingSenderId: '104895741192',
    projectId: 'employee-576ed',
    storageBucket: 'employee-576ed.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAXUHCwamiCYLrkolNkzO6RyN1eGuO7C0c',
    appId: '1:104895741192:ios:c4feb8c209a6e641f540bd',
    messagingSenderId: '104895741192',
    projectId: 'employee-576ed',
    storageBucket: 'employee-576ed.appspot.com',
    iosBundleId: 'com.example.employeesApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAXUHCwamiCYLrkolNkzO6RyN1eGuO7C0c',
    appId: '1:104895741192:ios:9780ad3e4913ed01f540bd',
    messagingSenderId: '104895741192',
    projectId: 'employee-576ed',
    storageBucket: 'employee-576ed.appspot.com',
    iosBundleId: 'com.example.employeesApp.RunnerTests',
  );
}
